CREATE WAREHOUSE IF NOT EXISTS DBT_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS AIR_QUALITY_DB;

CREATE SCHEMA IF NOT EXISTS AIR_QUALITY_DB.RAW;
CREATE SCHEMA IF NOT EXISTS AIR_QUALITY_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS AIR_QUALITY_DB.MARTS;

CREATE ROLE IF NOT EXISTS DBT_ROLE;

GRANT USAGE ON WAREHOUSE DBT_WH TO ROLE DBT_ROLE;
GRANT USAGE ON DATABASE AIR_QUALITY_DB TO ROLE DBT_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE AIR_QUALITY_DB TO ROLE DBT_ROLE;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA AIR_QUALITY_DB.RAW TO ROLE DBT_ROLE;
GRANT CREATE TABLE, CREATE VIEW
  ON SCHEMA AIR_QUALITY_DB.STAGING TO ROLE DBT_ROLE;
GRANT CREATE TABLE, CREATE VIEW
  ON SCHEMA AIR_QUALITY_DB.MARTS TO ROLE DBT_ROLE;
